/**
 * Chat System Types
 *
 * Types for the AI chat interface that generates widgets and answers questions.
 */

import type { WidgetConfig } from "./widget";

export type MessageRole = "user" | "assistant" | "system" | "function";

export interface ChatMessage {
  id: string;
  role: MessageRole;
  content: string;
  createdAt: Date;

  /** Widget generated by this message */
  widget?: WidgetConfig;

  /** Function call details */
  functionCall?: {
    name: string;
    arguments: Record<string, unknown>;
    result?: unknown;
  };

  /** Referenced data IDs */
  references?: {
    leads?: string[];
    matches?: string[];
    insights?: string[];
  };

  /** Token usage */
  tokens?: {
    prompt: number;
    completion: number;
  };
}

export interface ChatConversation {
  id: string;
  title: string;
  organizationId: string;
  userId: string;
  messages: ChatMessage[];
  summary?: string;
  createdAt: string;
  updatedAt: string;
}

export interface ChatState {
  conversationId?: string;
  messages: ChatMessage[];
  isLoading: boolean;
  error?: string;

  /** Pending widget to be added to dashboard */
  pendingWidget?: WidgetConfig;
}

/** Actions the AI can take */
export type AIAction =
  | { type: "generate_widget"; widget: WidgetConfig }
  | { type: "show_data"; data: Record<string, unknown>[]; title: string }
  | { type: "navigate"; path: string }
  | { type: "filter"; filters: Record<string, unknown> }
  | { type: "export"; format: "csv" | "pdf"; data: unknown };

/** Tool definitions for the AI */
export interface AITool {
  name: string;
  description: string;
  parameters: Record<string, unknown>;
}

export const AI_TOOLS: AITool[] = [
  {
    name: "generate_widget",
    description: "Generate a dashboard widget based on user request. Returns a widget configuration that renders a chart, table, or metric.",
    parameters: {
      type: "object",
      properties: {
        widget_type: {
          type: "string",
          enum: ["bar", "line", "area", "donut", "table", "metric", "list", "sparkline"],
          description: "Type of visualization",
        },
        title: {
          type: "string",
          description: "Widget title",
        },
        description: {
          type: "string",
          description: "Brief description of what the widget shows",
        },
        query: {
          type: "object",
          description: "Data query configuration",
          properties: {
            source: {
              type: "string",
              enum: ["v_lead_attribution", "v_source_summary", "v_team_summary", "v_agent_summary"],
            },
            groupBy: {
              type: "array",
              items: { type: "string" },
            },
            dateRange: {
              type: "object",
              properties: {
                preset: { type: "string", enum: ["7d", "30d", "90d", "ytd"] },
              },
            },
          },
        },
        visualization: {
          type: "object",
          description: "How to display the data",
        },
      },
      required: ["widget_type", "title", "query"],
    },
  },
  {
    name: "query_leads",
    description: "Query leads with filters. Use this to answer questions about lead counts, sources, and statuses.",
    parameters: {
      type: "object",
      properties: {
        source: { type: "string", description: "Lead source filter (zillow, realtor_com, etc.)" },
        match_status: { type: "string", enum: ["pending", "matched", "unmatched", "review"] },
        date_from: { type: "string", description: "Start date (ISO format)" },
        date_to: { type: "string", description: "End date (ISO format)" },
        limit: { type: "number", description: "Max results" },
      },
    },
  },
  {
    name: "get_summary",
    description: "Get summary statistics for sources, teams, or agents.",
    parameters: {
      type: "object",
      properties: {
        type: { type: "string", enum: ["source", "team", "agent"] },
      },
      required: ["type"],
    },
  },
  {
    name: "semantic_search",
    description: "Search leads using natural language. Finds leads matching a description.",
    parameters: {
      type: "object",
      properties: {
        query: { type: "string", description: "Natural language search query" },
        limit: { type: "number", default: 10 },
      },
      required: ["query"],
    },
  },
];
